### ISSUE TITLE
Wrong name on quote for poem

### ISSUE THREAD

**Issue by j4cobgarby** [pathtrk/ariake-dark-syntax#1]
Hm. Well not sure if it's an 'issue' as such, but it's actually Mibo no Tadamine.
https://en.wikipedia.org/wiki/Mibu_no_Tadamine

**Comment by pathtrk** [comment]
@j4cobgarby Thanks, I didn't realize his last name should be separated in English. I'll update it in the next patch release.

**Comment by pathtrk** [comment]
@j4cobgarby Thank you for letting me know. I updated the poet's name. 
Please feel free to reopen this issue.
