### ISSUE TITLE
Deprecation with Atom 1.13

### ISSUE THREAD

**Issue by didierfranc** [pathtrk/ariake-dark-syntax#2]
<img width="1430" alt="capture d ecran 2016-12-03 a 18 48 13" src="https://cloud.githubusercontent.com/assets/14132464/20861153/2f27b15e-b989-11e6-95e0-a3adaecf38a1.png">

**Comment by pathtrk** [comment]
@didierfranc Thanks for checking it out. It seems the current stable release of Atom is 1.12.6. So I'll plan to adapt 1.13.0 on the next major update of this syntax.

**Comment by pathtrk** [comment]
I might need to install Atom beta for providing code fix in advance of the changes.

**Comment by NetOpWibby** [comment]
I just installed this beautiful theme and came here to report on the deprecation. So pretty! Looking forward to the update.

**Comment by pathtrk** [comment]
@NetOperatorWibby Thank you for letting me know! I just have fixed the deprecation. Please update the theme via atom settings tab.

**Comment by pathtrk** [comment]
I'd like to close this issue as I fixed it, Yet Please feel free to reopen.

**Comment by NetOpWibby** [comment]
Yup, it's fixed. Thank you!

**Comment by thenobleone** [comment]
You rock! Love this theme.
