### ISSUE TITLE
Brighter comments

### ISSUE THREAD

**Issue by onetrev** [pathtrk/ariake-dark-syntax#3]
Great theme! And no worries if you want to close this item right away, it is a bit of personal preference thing.... But any chance of making the comment styling a bit brighter, and thereby easier to read? I find a lot of themes tend to make them fade into the bg too much, but comments serve a role so I personally believe they should be somewhat readable. :)

Thanks either way!

**Comment by pathtrk** [comment]
Thanks! @onetrev 

I didn't realize when I first composed the color scheme, but yes I think you're right. So I will modify comment color a little brighter soon.

Do you have certain value in your mind?
The current color is ```hsl(228, 17%, 40%)``` against the background ```hsl(228, 13%, 19%)```

And If you need to tweak the syntax color now, You can write additional style to style.less like;

```
atom-text-editor::shadow {
  .comment {
    color: white;
  }
  .punctuation {
    &.definition {
      &.comment {
        color: white;
      }
    }
  }
}
```
Thanks anyway!

**Comment by pathtrk** [comment]
@onetrev I added 5% more brightness to comment color. If you need further modification, Please refer the code I submitted before this comment. And opening issues for aesthetics or readability subjects are always welcome.

**Comment by onetrev** [comment]
Hello! Thanks for making this update. I like it! Big improvement for sure. I think I was thinking maybe something a bit brighter, `hsl(228, 20%, 57%)`, but that might be going too far.
