### ISSUE TITLE
Syntactic coloring

### ISSUE THREAD

**Issue by Crazy-Cactus** [pathtrk/ariake-dark-syntax#5]
Hello,
I have lost the Syntactic coloring with the new version

**Comment by Deharlan** [comment]
I have the same problem

**Comment by Deharlan** [comment]
My solution was install the old version 0.0.6
**with the command:**
`apm install ariake-dark-syntax@0.0.6`

First of all, **uninstall** the `ariake-dark-syntax`, and so install a old version

**Comment by pathtrk** [comment]
Hi @Crazy-Cactus, @Deharlan
Thanks for letting me know the issue.

Which version of Atom are you on? 
Atom 1.13.0 should work with the latest Ariake. Please try v0.1.1 of the theme with the latest stable Atom.

Or does it luck the syntactic coloring for a certain language? If so, I'd be grateful If you could provide which language the theme is missing.

**Comment by caudatecoder** [comment]
Thanks @pathtrk 
In Atom 1.13.0 everything works well

Maybe you should update _engines_ section in `package.json` to prevent people with older versions from getting incompatible update.

**Comment by Deharlan** [comment]
Thanks @pathtrk 
Its works very well, good job and good theme

**Comment by pathtrk** [comment]
@caudatecoder 
Thanks so much for letting me know about _engines_ section in ```package.json```. I completely missed it! I updated the package.json with engines section for corresponding atom version.

@Deharlan 
Glad to hear the theme works!

**Comment by pathtrk** [comment]
As I updated the theme with 0.1.2 release for deprecation and compatibility, I'll close this issue.

Thanks folks! Please feel free to reopen this anytime.
