### ISSUE TITLE
Light version

### ISSUE THREAD

**Issue by felixsanz** [pathtrk/ariake-dark-syntax#6]
If this is the "dark" version, are you planing to release a light one?

**Comment by pathtrk** [comment]
@felixsanz I'm not planning a light version of this theme for this moment. But I might start to write the light version when I get less busy. If you're interested in extending this theme, Contributions are always welcome.

**Comment by mblair** [comment]
@felixsanz there's this: https://github.com/ragmha/ariake-light-syntax

**Comment by felixsanz** [comment]
@mblair what happened to it?

**Comment by mblair** [comment]
@felixsanz oof, no clue! Might be worth pinging @ragmha.

**Comment by ragmha** [comment]
sorry about that, Anyone is welcome to contribute to the repo [ariake-light-syntax](https://github.com/ragmha/ariake-light-syntax)

**Comment by pathtrk** [comment]
@mblair @felixsanz @ragmha 
Hi, I close this issue hoping ariake-light-syntax helps your coding. Please leave your comments if you have questions or requests for the __dark__ syntax that I maintain.
